name: website test

on:
  push:
    branches:
      - main
      - dev
      - website-dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        
      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.11.5"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black

      - name: Run flake8 (Line)
        run: flake8 .

      - name: Check code format with black
        run: black --check .

      - name: test application
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_HOST: mongodb
          MONGO_PORT: 27017
        run: pytest
      
